// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH6BpmOApr9UdBv9WAwQpTgrOesUq1QoU',
    appId: '1:426283843862:web:0f47f492b42f7a606c9037',
    messagingSenderId: '426283843862',
    projectId: 'ar-furnish-10268',
    authDomain: 'ar-furnish-10268.firebaseapp.com',
    storageBucket: 'ar-furnish-10268.firebasestorage.app',
    measurementId: 'G-RRVZXZBKNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTyfMgZ6CI5V0aaLIBePr6M_UrUC7Qts',
    appId: '1:426283843862:android:ffe14c16bf08d6636c9037',
    messagingSenderId: '426283843862',
    projectId: 'ar-furnish-10268',
    storageBucket: 'ar-furnish-10268.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG44CyQFStjP42eDkeUguwX0rhLHzYgT4',
    appId: '1:426283843862:ios:97f887249ac0fc996c9037',
    messagingSenderId: '426283843862',
    projectId: 'ar-furnish-10268',
    storageBucket: 'ar-furnish-10268.firebasestorage.app',
    androidClientId: '426283843862-d5a3nr46nq1laa6bgu4qi503cs4596an.apps.googleusercontent.com',
    iosClientId: '426283843862-kvhfrovb4mdlrk1obefor6knpu0rc4ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPenal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG44CyQFStjP42eDkeUguwX0rhLHzYgT4',
    appId: '1:426283843862:ios:97f887249ac0fc996c9037',
    messagingSenderId: '426283843862',
    projectId: 'ar-furnish-10268',
    storageBucket: 'ar-furnish-10268.firebasestorage.app',
    androidClientId: '426283843862-d5a3nr46nq1laa6bgu4qi503cs4596an.apps.googleusercontent.com',
    iosClientId: '426283843862-kvhfrovb4mdlrk1obefor6knpu0rc4ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPenal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH6BpmOApr9UdBv9WAwQpTgrOesUq1QoU',
    appId: '1:426283843862:web:6f979e5c1952fe6e6c9037',
    messagingSenderId: '426283843862',
    projectId: 'ar-furnish-10268',
    authDomain: 'ar-furnish-10268.firebaseapp.com',
    storageBucket: 'ar-furnish-10268.firebasestorage.app',
    measurementId: 'G-WZQK7KTMZH',
  );
}
